BEGIN;
SET LOCAL search_path TO public;

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    email text NOT NULL UNIQUE,
    phone text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    price numeric(10, 2) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_email text NOT NULL REFERENCES users (email),
    product_id integer NOT NULL REFERENCES products (id),
    qty integer NOT NULL CHECK (qty > 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE support_tickets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_email text NOT NULL REFERENCES users (email),
    order_id integer NOT NULL REFERENCES orders (id),
    subject text NOT NULL,
    status text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

INSERT INTO users (full_name, email, phone, created_at, updated_at) VALUES
    ('Avery Brooks', 'avery.brooks@example.test', '+1-202-555-0101', '2025-01-05 09:15:00+00', '2025-01-05 09:15:00+00'),
    ('Jordan Kim', 'jordan.kim@example.test', '+1-202-555-0102', '2025-01-08 11:30:00+00', '2025-01-08 11:30:00+00'),
    ('Morgan Patel', 'morgan.patel@example.test', '+1-202-555-0103', '2025-01-12 14:05:00+00', '2025-01-12 14:05:00+00'),
    ('Riley Chen', 'riley.chen@example.test', '+1-202-555-0104', '2025-01-17 08:45:00+00', '2025-01-17 08:45:00+00'),
    ('Casey Rivera', 'casey.rivera@example.test', '+1-202-555-0105', '2025-01-21 16:20:00+00', '2025-01-21 16:20:00+00'),
    ('Taylor Singh', 'taylor.singh@example.test', '+1-202-555-0106', '2025-01-26 10:10:00+00', '2025-01-26 10:10:00+00'),
    ('Quinn Foster', 'quinn.foster@example.test', '+1-202-555-0107', '2025-02-02 13:35:00+00', '2025-02-02 13:35:00+00'),
    ('Jamie Okafor', 'jamie.okafor@example.test', '+1-202-555-0108', '2025-02-09 12:00:00+00', '2025-02-09 12:00:00+00'),
    ('Drew Morgan', 'drew.morgan@example.test', '+1-202-555-0109', '2025-02-15 09:50:00+00', '2025-02-15 09:50:00+00'),
    ('Skyler Diaz', 'skyler.diaz@example.test', '+1-202-555-0110', '2025-02-22 15:25:00+00', '2025-02-22 15:25:00+00');

INSERT INTO products (name, price, created_at, updated_at) VALUES
    ('Everyday Backpack', 64.00, '2025-01-02 10:00:00+00', '2025-01-02 10:00:00+00'),
    ('Insulated Travel Mug', 24.50, '2025-01-03 10:00:00+00', '2025-01-03 10:00:00+00'),
    ('Wireless Desk Lamp', 48.00, '2025-01-04 10:00:00+00', '2025-01-04 10:00:00+00'),
    ('Cotton Throw Blanket', 72.00, '2025-01-06 10:00:00+00', '2025-01-06 10:00:00+00'),
    ('Ceramic Planter Set', 36.00, '2025-01-07 10:00:00+00', '2025-01-07 10:00:00+00');

INSERT INTO orders (buyer_email, product_id, qty, created_at, updated_at) VALUES
    ('avery.brooks@example.test', 1, 1, '2025-02-24 10:15:00+00', '2025-02-24 10:15:00+00'),
    ('jordan.kim@example.test', 2, 2, '2025-02-25 11:20:00+00', '2025-02-25 11:20:00+00'),
    ('morgan.patel@example.test', 3, 1, '2025-02-26 12:05:00+00', '2025-02-26 12:05:00+00'),
    ('riley.chen@example.test', 4, 1, '2025-02-27 13:40:00+00', '2025-02-27 13:40:00+00'),
    ('casey.rivera@example.test', 5, 3, '2025-02-28 09:30:00+00', '2025-02-28 09:30:00+00'),
    ('taylor.singh@example.test', 1, 2, '2025-03-01 14:10:00+00', '2025-03-01 14:10:00+00'),
    ('quinn.foster@example.test', 2, 1, '2025-03-02 10:50:00+00', '2025-03-02 10:50:00+00'),
    ('jamie.okafor@example.test', 3, 2, '2025-03-03 16:25:00+00', '2025-03-03 16:25:00+00'),
    ('drew.morgan@example.test', 4, 1, '2025-03-04 08:55:00+00', '2025-03-04 08:55:00+00'),
    ('skyler.diaz@example.test', 5, 1, '2025-03-05 12:35:00+00', '2025-03-05 12:35:00+00'),
    ('avery.brooks@example.test', 2, 1, '2025-03-06 15:05:00+00', '2025-03-06 15:05:00+00'),
    ('jordan.kim@example.test', 3, 1, '2025-03-07 09:45:00+00', '2025-03-07 09:45:00+00'),
    ('morgan.patel@example.test', 4, 2, '2025-03-08 11:15:00+00', '2025-03-08 11:15:00+00'),
    ('riley.chen@example.test', 5, 1, '2025-03-09 13:25:00+00', '2025-03-09 13:25:00+00'),
    ('casey.rivera@example.test', 1, 1, '2025-03-10 10:40:00+00', '2025-03-10 10:40:00+00'),
    ('taylor.singh@example.test', 2, 3, '2025-03-11 14:55:00+00', '2025-03-11 14:55:00+00'),
    ('quinn.foster@example.test', 3, 1, '2025-03-12 08:20:00+00', '2025-03-12 08:20:00+00'),
    ('jamie.okafor@example.test', 4, 1, '2025-03-13 12:10:00+00', '2025-03-13 12:10:00+00'),
    ('drew.morgan@example.test', 5, 2, '2025-03-14 16:45:00+00', '2025-03-14 16:45:00+00'),
    ('skyler.diaz@example.test', 1, 1, '2025-03-15 09:05:00+00', '2025-03-15 09:05:00+00');

INSERT INTO support_tickets (requester_email, order_id, subject, status, created_at, updated_at) VALUES
    ('avery.brooks@example.test', 1, 'Backpack strap adjustment', 'closed', '2025-02-25 08:30:00+00', '2025-02-26 10:00:00+00'),
    ('jordan.kim@example.test', 2, 'Mug lid replacement', 'open', '2025-02-26 09:15:00+00', '2025-02-26 09:15:00+00'),
    ('morgan.patel@example.test', 3, 'Lamp pairing instructions', 'in_progress', '2025-02-27 11:40:00+00', '2025-02-28 08:20:00+00'),
    ('riley.chen@example.test', 4, 'Blanket care question', 'closed', '2025-02-28 14:05:00+00', '2025-03-01 09:10:00+00'),
    ('casey.rivera@example.test', 5, 'Planter set arrived damaged', 'open', '2025-03-01 10:25:00+00', '2025-03-01 10:25:00+00'),
    ('taylor.singh@example.test', 6, 'Update delivery address', 'closed', '2025-03-02 13:50:00+00', '2025-03-02 14:30:00+00'),
    ('quinn.foster@example.test', 7, 'Mug color availability', 'closed', '2025-03-03 15:20:00+00', '2025-03-04 10:45:00+00'),
    ('jamie.okafor@example.test', 8, 'Lamp brightness settings', 'in_progress', '2025-03-04 08:10:00+00', '2025-03-05 12:00:00+00'),
    ('drew.morgan@example.test', 9, 'Blanket gift receipt', 'closed', '2025-03-05 16:00:00+00', '2025-03-06 09:25:00+00'),
    ('skyler.diaz@example.test', 10, 'Planter drainage advice', 'open', '2025-03-06 11:35:00+00', '2025-03-06 11:35:00+00');

COMMIT;
